version: "2"

services:
  client:
    build: 
      context: ./client
    container_name: medicords-client
    stdin_open: true
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network
  server:
    build: 
      context: ./server
    container_name: medicords-server
    env_file:
      - "./server/config.env"
    ports:
      - "4000:4000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
